<a href="https://colab.research.google.com/github/leandroleao2k/PyLeao/blob/main/PreProcessamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pre-processamento com a base do Kaggle

> Bloco com recuo

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import altair as alt

atletas = pd.read_csv("https://raw.githubusercontent.com/andrefmb/EDA_Olimpiadas/master/athlete_events.csv")
noc = pd.read_csv("https://raw.githubusercontent.com/andrefmb/EDA_Olimpiadas/master/noc_regions.csv")

#Estrutura
atletas.head()
noc.head()
#Verificar Missing Data

   ID                      Name  ...                             Event  Medal
0   1                 A Dijiang  ...       Basketball Men's Basketball    NaN
1   2                  A Lamusi  ...      Judo Men's Extra-Lightweight    NaN
2   3       Gunnar Nielsen Aaby  ...           Football Men's Football    NaN
3   4      Edgar Lindenau Aabye  ...       Tug-Of-War Men's Tug-Of-War   Gold
4   5  Christine Jacoba Aaftink  ...  Speed Skating Women's 500 metres    NaN

[5 rows x 15 columns]